# Generated by Django 3.1.7 on 2022-05-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.chat'),
            preserve_default=False,
        ),
    ]
