# Generated by Django 3.1.7 on 2022-05-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_mensaje_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='nombre',
            new_name='roomName',
        ),
    ]
