# Generated by Django 3.1.7 on 2022-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220520_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unreadCount',
            field=models.IntegerField(default=1),
        ),
    ]
