# Generated by Django 3.1.7 on 2022-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_chat_unreadcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='disableActions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='disableReactions',
            field=models.BooleanField(default=True),
        ),
    ]
