# Generated by Django 3.1.7 on 2022-06-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20220524_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
