# Generated by Django 3.1.7 on 2022-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220602_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='unreadCount',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='saved',
            field=models.BooleanField(default=True),
        ),
    ]
