# Generated by Django 4.0.4 on 2022-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_order_paymethod_alter_archivomensaje_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method_data',
            field=models.TextField(null=True),
        ),
    ]
