# Generated by Django 4.0.4 on 2022-07-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_total_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('R', 'En revision'), ('P', 'Preparando'), ('C', 'En camino'), ('E', 'Entregado')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
