# Generated by Django 4.0.4 on 2022-07-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_order_client_location_order_raison_cancel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='locate_a',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='locate_l',
        ),
    ]
