# Generated by Django 4.0.4 on 2022-07-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_locate_a_perfil_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='contract_id',
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_shop',
            field=models.TextField(default='dinoir.near'),
            preserve_default=False,
        ),
    ]
