# Generated by Django 4.0.4 on 2022-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_orderdetail_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
