# Generated by Django 4.0.4 on 2022-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_deliver_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
