# Generated by Django 4.0.4 on 2022-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_orderdetail_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_shop',
            field=models.TextField(default='asdasd'),
            preserve_default=False,
        ),
    ]
