# Generated by Django 4.0.4 on 2022-07-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_order_name_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('R', 'En revision'), ('N', 'Pendiente'), ('P', 'Preparando'), ('C', 'En camino'), ('E', 'Entregado'), ('B', 'Recibido'), ('X', 'Cancelado')], default='R', max_length=1),
        ),
    ]
