# Generated by Django 4.0.4 on 2022-07-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_order_chat_alter_order_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion',
            field=models.TextField(default='carabobo'),
            preserve_default=False,
        ),
    ]
