# Generated by Django 4.0.4 on 2022-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_order_deliver_cost_alter_order_name_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='possible',
            field=models.ManyToManyField(to='backend.perfil'),
        ),
    ]
